- name: Deploy prepare
  include: prepare.yml
  tags: ['mars-prepare']

- name: Install RVM
  include_role:
    name: rvm
    become: yes
  tags: ['mars-ruby']

- name: Install nginx
  include_role:
    name: nginx
    become: yes
  tags: ['mars-nginx']

- name: Install python3-psycopg2 for postgresql
  include: apt.yml name=python3-psycopg2
  tags: ['mars-db']

- name: Install postgresql
  include_role:
    name: postgresql
    become: yes
  tags: ['mars-db']

- name: Install gem dependencies
  include: apt.yml name={{ item }}
  tags: ['mars-gem']
  with_items:
    - libpq-dev # for pg gem
    - nodejs # for uglifier (assets pipeline)
    - imagemagick # for carrierwave
