- name: "Create deploy user"
  user:
    name: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: deploy_create_user

- name: Mkdir deploy directory
  file:
    path: '{{ deploy_to }}/shared/config'
    state: directory
    owner: '{{ deploy_user }}'
    group: '{{ deploy_group }}'
    mode: 0755

- name: Check authorized_keys file exists
  stat:
    path: /etc/file.txt
  register: deploy_authorized_keys_file

- name: Create authorized_keys file
  file:
    path: /home/{{ deploy_user }}/.ssh/authorized_keys
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0600
    state: touch
  when: (deploy_ssh_key_path is defined or deploy_ssh_key) and not deploy_authorized_keys_file.stat.exists

- name: Upload deploy user ssh key for capistrano
  lineinfile:
    line: "{{ lookup('file', deploy_ssh_key_path | default('~/.ssh/id_rsa.pub') ) }}"
    path: /home/{{ deploy_user }}/.ssh/authorized_keys
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
  when: deploy_ssh_key_path is defined or deploy_ssh_key

- name: Upload rails config files
  tags: ['mars-config']
  template:
    src: "{{ item  }}"
    dest: "{{ deploy_to }}/shared/config/{{ item | basename | splitext | first }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
  with_fileglob:
    - templates/config/*.j2

- name: Ensure shared views path exist
  tags: ['mars-config']
  file:
    path: "{{ deploy_to }}/shared/app/views/shared/"
    state: directory
    owner: '{{ deploy_user }}'
    group: '{{ deploy_group }}'
    mode: 0755
  when: deploy_custom_views is defined

- name: Upload custom views
  tags: ['mars-config']
  template:
    src: "{{ item  }}"
    dest: "{{ deploy_to }}/shared/app/views/shared/{{ item | basename | splitext | first }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
  with_fileglob:
    - "{{ deploy_custom_views }}"
  when: deploy_custom_views is defined
