- name: Add backports source list
  copy: src=backports.list
        dest=/etc/apt/sources.list.d/backports.list
  register: source

- name: Update apt-get cache
  apt: update_cache=yes
  when: source.changed

- name: Install Java Runtime Environment
  apt: pkg=openjdk-8-jdk state=present default_release=jessie-backports
