
# basic

deploy_app: mars
deploy_to: /var/www/{{ deploy_app }}
deploy_user: deploy
deploy_group: www-data
deploy_domain: mars.john1king.com
deploy_ruby_version: 2.4.1

database_name: mars
database_user: deploy

deploy_use_https: yes

deploy_nginx_server_conf: "{{ lookup('template', 'nginx/server.conf.j2') }}"

deploy_nginx_http_conf: |
  listen 80;
  {{ deploy_nginx_server_conf }}

deploy_nginx_default_conf: |
  listen 80;
  server_name "{{ deploy_domain }}";
  return 301 https://$server_name$request_uri;

deploy_nginx_https_conf: |
  listen 443;
  ssl on;
  ssl_certificate /etc/letsencrypt/live/{{ deploy_domain }}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/{{ deploy_domain }}/privkey.pem;
  {{ deploy_nginx_server_conf }}

deploy_nginx_upstream_conf: |
  upstream {{ deploy_app }} {
    server unix://{{ deploy_to }}/shared/tmp/sockets/puma.sock;
  }


