
# basic

deploy_app: mars
deploy_to: /var/www/{{ deploy_app }}
deploy_user: deploy
deploy_group: www-data
deploy_domain: mars.john1king.com
deploy_ruby_version: 2.4.1

database_name: mars
database_user: deploy

deploy_nginx_default: |
  listen 80;
  server_name "{{ deploy_domain }}";
  return 301 https://$server_name$request_uri;

deploy_nginx_https: |
  listen 443;
  ssl on;
  ssl_certificate /etc/letsencrypt/live/{{ deploy_domain }}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/{{ deploy_domain }}/privkey.pem;
  server_name "{{ deploy_domain }}";
  root "{{ deploy_to }}/current/public";
  access_log {{ deploy_to }}/shared/log/nginx.access.log;
  error_log {{ deploy_to }}/shared/log/nginx.error.log;
  try_files $uri @{{ deploy_app }};
  location ^~ /assets/ {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
  }
  location @{{ deploy_app }} {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://{{ deploy_app }};
  }
  error_page 500 502 503 504 /500.html;
  client_max_body_size 10M;
  keepalive_timeout 10;

deploy_nginx_upstream: |
  upstream {{ deploy_app }} {
    server unix://{{ deploy_to }}/shared/tmp/sockets/puma.sock;
  }


