- name: Add source list
  shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

- name: Add apt repository key
  shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

- name: Install postgresql client
  apt: update_cache=yes cache_valid_time=3600 pkg=postgresql-client-{{ postgresql_client_version }} state=present
